name: Generate GitHub Streak

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  streak:
    runs-on: ubuntu-latest

    steps:
      - name: Generate streak SVG
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          USERNAME: ashishrathi21
          OUTPUT_PATH: streak.svg
          THEME: tokyonight
          HIDE_BORDER: true

      - name: Commit streak SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution streak"
          add: "streak.svg"
